import { PageLayout } from '@/Layout';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <PageLayout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <div data-scroll-section>
          <h1 className='title' data-scroll data-scroll-direction='horizontal' data-scroll-speed='6'>
            Welcome to <a href='https://nextjs.org'>Next.js!</a>
          </h1>

          <p className="description" data-scroll data-scroll-direction='horizontal' data-scroll-speed='-5'>
            Get started by editing <code className="code">pages/index.tsx</code>
          </p>

          <div className="grid">
            <a href='https://nextjs.org/docs' className="card">
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href='https://nextjs.org/learn' className="card">
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a href='https://github.com/vercel/next.js/tree/master/examples' className="card">
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              className="card"
            >
              <h2>Deploy &rarr;</h2>
              <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
            </a>
          </div>
        </div>

        <div data-scroll-section>
          <p className="description" data-scroll data-scroll-speed='1'>
            Simple Scroll Speed
          </p>

          <div className="grid">
            {[...Array(10)].map((_, i) => (
              <div className="card" key={i} data-scroll data-scroll-speed={i}>
                <h2>data-scroll-speed</h2>
                <code>{`<div data-scroll data-scroll-speed="${i}"></div>`}</code>
              </div>
            ))}
          </div>
        </div>

        <div data-scroll-section>
          <p className="description" data-scroll data-scroll-speed='1'>
            Scroll Delay
          </p>

          <div className="grid">
            {[...Array(10)].map((_, i) => (
              <div className="card" key={i} data-scroll data-scroll-speed='1' data-scroll-delay={i / 100}>
                <h2>data-scroll-delay</h2>
                <code>{`<div data-scroll data-scroll-speed="1" data-scroll-delay="${i / 100}"></div>`}</code>
              </div>
            ))}
          </div>
        </div>

        <div data-scroll-section>
          <p className="description" data-scroll data-scroll-speed='1'>
            Scroll Speed + Delay
          </p>

          <div className="grid">
            {[...Array(10)].map((_, i) => (
              <div className="card" key={i} data-scroll data-scroll-speed={i} data-scroll-delay={i / 100}>
                <h2>data-scroll-delay</h2>
                <code>{`<div data-scroll data-scroll-speed="${i}" data-scroll-delay="${i / 100}"></div>`}</code>
              </div>
            ))}
          </div>
        </div>
      </main>
    </PageLayout>
  );
};

export default Home;
